source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'XAssets_Example' do
    pod "XAssets", :path => "../"
    
    pod 'ReactiveCocoa', '= 4.0.0'
    pod 'SDWebImage', '~> 3.7.0'
    
    target 'XAssets_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 0.9.0'
        pod 'Nimble', '~> 3.1.0'
    end
end


